### ISSUE TITLE
Adding har777  to the osm-edit-report

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#14]
@Rub21 

I added [har777](https://www.openstreetmap.org/user/har777) to the [add_user.sql](https://github.com/mapbox/osm-edit-report/blob/mb-pages/query/add_user.sql) table.

![edit](https://cloud.githubusercontent.com/assets/3190951/7082966/5be17810-df79-11e4-8fcc-7ddeb36ed852.png)

The graph still does not show his OSM username. 

![screen shot 2015-04-10 at 12 14 02 pm](https://cloud.githubusercontent.com/assets/3190951/7083090/29d15e38-df7b-11e4-88e1-2ac8077cd528.png)

_I also found out the karitotp is not in the table but her name shows up on the graph_

cc- @planemad

**Comment by Rub21** [comment]
@shravan91 @planemad :

I added har777 user in our database,:
![screenshot from 2015-04-10 09 39 23](https://cloud.githubusercontent.com/assets/1152236/7090020/b9cf21ca-df65-11e4-8f91-e79560ea2a40.png)
![screenshot from 2015-04-10 09 39 59](https://cloud.githubusercontent.com/assets/1152236/7090022/bbd2df20-df65-11e4-87f6-4338769da371.png)

from now on the app is going to track to user har777
