### ISSUE TITLE
Adding Chetan_Gowda

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#15]
@Rub21 

I have added [Chetan_Gowda](https://www.openstreetmap.org/user/Chetan_Gowda) to the [add_user.sql](https://github.com/mapbox/osm-edit-report/blob/mb-pages/query/add_user.sql) table. @Rub21 - could you please update on the server.

**Comment by Rub21** [comment]
@shravan91 : sorry for not jump early,  but i am in Lima and I forgot my table in Ayacucho.  on my tablet contain the two-factor-authentication . and now  I can not access to serve. :( , Soon as possible when i come back, i will add to `Chetan_Gowda` 

Thanks for add him, on query.

**Comment by Rub21** [comment]
@shravan91 , done here
![image](https://cloud.githubusercontent.com/assets/1152236/7230295/fc85e0f2-e731-11e4-8c69-bf0793a7e435.png)
