### ISSUE TITLE
Adding Ramya and Kshitiz

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#17]
@Rub21 - Added users @ramyaragupathy and Kshitiz

![screen shot 2015-05-04 at 12 45 58 pm](https://cloud.githubusercontent.com/assets/3190951/7449851/943bf092-f25b-11e4-8629-addd5c17ade2.png)

> [Ramya Ragupathy](http://www.openstreetmap.org/user/Ramya%20Ragupathy)
> [ksharma198](https://www.openstreetmap.org/user/ksharma198)

**Comment by Rub21** [comment]
done
