### ISSUE TITLE
Removed user kshitiz sharma from the OSM edit report

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#18]
@Rub21 -

I have removed kshitiz sharma  from the edit report. 

![feedback](https://cloud.githubusercontent.com/assets/3190951/7580843/84d4e2aa-f899-11e4-8a2f-a252a4450938.gif)
###### Next Actions
- [x] @Rub21 to run the server
- [x] @shravan91 to check if the graph is updated

**Comment by Rub21** [comment]
@shravan91   done!
![image](https://cloud.githubusercontent.com/assets/1152236/7581558/29617b3c-f8a2-11e4-8b51-1d167d644cd0.png)

**Comment by shravan91** [comment]
@Rub21 - Thanks! Checked the graph! Closing this issue.
