### ISSUE TITLE
OSM-Edit-Report showing Zero edits

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#20]
@Rub21 -

[OSM-Edit-Report](https://www.mapbox.com/osm-edit-report/#d&2015-06-04&2015-06-09) is showing Zero edits for most of us. Can you look into this issue.

![screen shot 2015-06-10 at 2 29 44 pm](https://cloud.githubusercontent.com/assets/3190951/8078787/a53a525a-0f7d-11e5-8272-196f59d6acf1.png)
![screen shot 2015-06-10 at 2 29 37 pm](https://cloud.githubusercontent.com/assets/3190951/8078789/a733a9d0-0f7d-11e5-9a4c-0a2f61f9bd00.png)
#### Next Actions
- [ ] @Rub21 finds out the problem
- [ ] @shravan91 confirms that the OSM edit report is working with @Rub21 closes this ticket.

**Comment by shravan91** [comment]
Continuing on this ticket

The date on the graph does not go beyond the 9th of June.

![screen shot 2015-06-11 at 12 09 05 pm](https://cloud.githubusercontent.com/assets/3190951/8102570/b7962dea-103e-11e5-83e5-2068214121b0.png)

**Comment by Rub21** [comment]
@shravan91  now is working  https://www.mapbox.com/osm-edit-report/#d&2015-06-04&2015-06-12

those days I worked on server: something  https://github.com/mapbox/osm-edit-report-service

**Comment by Rub21** [comment]
Additionally i am working on new branch to improve: this https://github.com/mapbox/osm-edit-report/tree/dev
