### ISSUE TITLE
Adding Users : Jinal and Pratik to OSM-edit-report

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#21]
@Rub21 - I have added @pratikyadav and @jinalfoflia to the OSM Edit report

![screen shot 2015-06-15 at 3 10 51 pm](https://cloud.githubusercontent.com/assets/3190951/8157251/cb0fcbee-1370-11e5-9f94-253eed0ac43e.png)

Next Actions:
- [x] @Rub21 to update and run the script on the server to add them on the OSM-edit-report

**Comment by Rub21** [comment]
Done!
