### ISSUE TITLE
Added Nikhil

### ISSUE THREAD

**Issue by shravan91** [mapbox/osm-edit-report-deprecated#22]
@Rub21 - 

Added Nikhil Prabhakar U to OSM-edit report
#### Next Actions
- [x] @Rub21 deploys this change (5cc853710940d922cbc10ce91d86296898294268) on the server and closes the ticket

**Comment by Rub21** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/1152236/8455939/bd822a3a-1fcd-11e5-9711-5f795a7e648f.png)
