### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by srividyacb** [mapbox/osm-edit-report-deprecated#25]
[OSM Edit report](https://www.mapbox.com/osm-edit-report) graphs are not showing and it keeps loading up. 

![screenshot 2015-07-21 10 41 10](https://cloud.githubusercontent.com/assets/3423533/8793507/806ddfcc-2f95-11e5-99da-13c6d68754b6.png)

cc @Rub21

**Comment by geohacker** [comment]
Not relevant.
