### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-edit-report-deprecated#27]
<img width="949" alt="screen shot 2015-07-27 at 15 15 03" src="https://cloud.githubusercontent.com/assets/371666/8902973/50b48812-3472-11e5-8c63-45ddfb1546da.png">
<img width="481" alt="screen shot 2015-07-27 at 15 15 07" src="https://cloud.githubusercontent.com/assets/371666/8902972/50b1fc50-3472-11e5-87fe-c4b95938b9b1.png">

Something like ^?

**Comment by arunasank** [comment]
Add transparency to circle style.
Fix "Per Hour" data
Default to from and to time periods depending on what is selected from the dropdown.

**Comment by arunasank** [comment]
github picture API

**Comment by arunasank** [comment]
### Progress

**Things done**
- Both reports show punchcard style visualisation
- Circle sizes seems to be relative for the whole graph and not a particular axis
- Ticks and alignment of circles to a particular tick WORKS!

**To do**
- Default "From" and "To" dates if the values selected are more than the relevant duration. For example, if more than 7 day durations are selected for the "Per Day" selection default the "from" date to "Today -7" and the "to" date to "Today"
- Pictures of users from github API
- Tick labels for the "Per hour" selection needs to be done properly
- Make circles larger and transparent and fix styles for circles and text.

Can be forked from the [d3-visuals branch](https://github.com/arunasank/osm-edit-report/tree/d3-visuals) to test/develop. That's where the latest code is.

**Comment by geohacker** [comment]
@arunasank great progress. I can't seem to get this going though.

```
app.js:362:0 - TypeError: window.event is undefined
```

**Comment by arunasank** [comment]
@geohacker Can you try running it from my [fork](https://github.com/arunasank/osm-edit-report/tree/d3-visuals) and see if the issue persists?

**Comment by arunasank** [comment]
New [edit report](https://www.mapbox.com/osm-edit-report/) fixes this. Closing.
