### ISSUE TITLE
Adding total count to OSM edit report

### ISSUE THREAD

**Issue by pratikyadav** [mapbox/osm-edit-report-deprecated#35]
It would be really cool to have total count for all edits by the team members in a day. I have been using this information in the [weekly data activity ticket](https://github.com/mapbox/data/issues/1390). @Rub21  is it possible to add this?

cc @geohacker  @planemad

**Comment by planemad** [comment]
Also useful is to have a count of active mappers (>100 objects modified in the day) as we now have more members who are not full time into mapping.

So for a day it might be: Total team: 23, Active: 18

This can also help us calculate total edits/active mappers which gives the average of the teams edits in a day.

cc @maning

**Comment by arunasank** [comment]
I'll add this to my To-do list once I start working on the edit report. I am not sure if you've had a chance to look at [my fork](https://github.com/arunasank/osm-edit-report/tree/d3-visuals) of the edit report, but if you remember we had coloured circles of different sizes to show the edits for different contributors. 

Maybe we can show the edits of active mappers in a certain colour and the edits of other mappers in a certain colour?

**Comment by Rub21** [comment]
@pratikyadav @planemad 

> @Rub21 is it possible to add this? 

Yes is possible ,  I think to copy and paste  the next lines: 
- Functions to make the graph.
  https://github.com/mapbox/osm-edit-report/blob/mb-pages/public/js/app.js#L30-L66
-  Html to show the graph
  https://github.com/mapbox/osm-edit-report/blob/mb-pages/index.html#L64-L75
- Make a copy from output data. and cross the data to function
  https://github.com/mapbox/osm-edit-report/blob/mb-pages/public/js/app.js#L391
  Need to work here or in new function the date came for each user, just make the sum and show the result in the new graph.

@arunasank , I am really agree with you to improve this counter app :+1:

**Comment by arunasank** [comment]
Added total counts to https://www.mapbox.com/osm-edit-report/

Per chat w/ @planemad there's no need to add _Active_ users since we're sorting by edits/changesets.

Closing.
