### ISSUE TITLE
Objects modified count frozen at zero

### ISSUE THREAD

**Issue by ramyaragupathy** [mapbox/osm-edit-report-deprecated#38]
@Rub21 -

OSM-Edit-Report is showing Zero edits for most of us. Can you please look into this issue.
![screenshot 2015-11-19 17 03 06](https://cloud.githubusercontent.com/assets/12103383/11269799/85525e38-8edf-11e5-9875-faf0edc34867.png)
 cc @geohacker @batpad

**Comment by batpad** [comment]
cc @Rub21 any idea what's going on here?

**Comment by Rub21** [comment]
@batpad  I think is the cron process,  I restore the process again , I will figure out more, when i will be there.

**Comment by ramyaragupathy** [comment]
Edit count shows up on the page. No next actions, closing here.
