### ISSUE TITLE
errors loading older data

### ISSUE THREAD

**Issue by danbjoseph** [mapbox/osm-edit-report-deprecated#50]
When using the num_file and num_directory parameters from the readme it gave errors.
For --num_file=1 --num_directory=0
`No file found url:https://s3.amazonaws.com/osm-changesets/hour/000/000/001.osc.gz`
For --num_file=177 --num_directory=20
`No file found url:https://s3.amazonaws.com/osm-changesets/hour/000/020/177.osc.gz`

Was checking parameters for more recent files and at least with --num_file=1 --num_directory=25 it began running:

```
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/025/003.osc.gz ---> /tmp/003.osc
Process file :/tmp/003.osc
Remove file :/tmp/003.osc
fin
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/025/004.osc.gz ---> /tmp/004.osc
Process file :/tmp/004.osc
Remove file :/tmp/004.osc
fin
```

On another note, is this same load process used to keep database up-to-date after the initial load?

**Comment by danbjoseph** [comment]
Another error encountered:

```
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/028/370.osc.gz ---> /tmp/370.osc

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/tmp/370.osc'
```

**Comment by danbjoseph** [comment]
Also seems to hang occasionally? I let it sit  at 258.osc with nothing logged (never logged 'Process file') for at least 15 min. Stopped the process and started it again, it resumed logging things at less than 5secs per file. 

```
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/028/257.osc.gz ---> /tmp/257.osc
Process file :/tmp/257.osc
Remove file :/tmp/257.osc
fin
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/028/258.osc.gz ---> /tmp/258.osc
^Cubuntu@ip-172-31-27-95:/osm-edit-report$ node load/load.js --num_file=258 --num_directory=28 --user=ubuntu --password=osm --database=dbstatistic
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/028/258.osc.gz ---> /tmp/258.osc
Process file :/tmp/258.osc
Remove file :/tmp/258.osc
fin
```

**Comment by danbjoseph** [comment]
```
Start download : https://s3.amazonaws.com/osm-changesets/hour/000/028/865.osc.gz ---> /tmp/865.osc
Process file :/tmp/865.osc
Remove file :/tmp/865.osc
fin
error en insertarerror: value "36051" is out of range for type smallint
No file found url:https://s3.amazonaws.com/osm-changesets/hour/000/028/866.osc.gz
```

866 didn't exist yet but I'm not sure what the error is about

**Comment by Rub21** [comment]
@danbjoseph : 

You can change the url `https://s3.amazonaws.com/osm-changesets/hour/` by `http://planet.openstreetmap.org/replication/hour/` on https://github.com/mapbox/osm-edit-report/blob/mb-pages/load/src/download.js#L10  ,and then you can run the app for any dates since  2012-10-23 23:02
