### ISSUE TITLE
Update correct OSM user name

### ISSUE THREAD

**Issue by geochetan** [mapbox/osm-edit-report-deprecated#53]
Missing correct user names: `aarthy` and `jinalfoflia`.  These are the correct usernames of [Aarthy](https://github.com/aarthykc) and [Jinal Foflia](https://github.com/jinalfoflia). Can you guys update the query. 

![screen shot 2016-01-29 at 3 25 28 pm](https://cloud.githubusercontent.com/assets/6770741/12672478/9347f5b2-c69c-11e5-8328-1a90bf18177d.png)

![screen shot 2016-01-29 at 3 25 18 pm](https://cloud.githubusercontent.com/assets/6770741/12672500/bfcd4204-c69c-11e5-94f1-230260282579.png)

@Rub21 @arunasank

**Comment by Rub21** [comment]
ready! https://github.com/mapbox/osm-edit-report/blob/mb-pages/query/add_user.sql.
