### ISSUE TITLE
Missing updates since 11th March!

### ISSUE THREAD

**Issue by geochetan** [mapbox/osm-edit-report-deprecated#55]
@Rub21 @arunasank The updates are missing since 11th March. Can you check what is wrong?

![screen shot 2016-03-15 at 12 13 11 pm](https://cloud.githubusercontent.com/assets/6770741/13769678/934dc21a-eaa7-11e5-96a0-a0c668d0f77c.png)

**Comment by Rub21** [comment]
done!
![image](https://cloud.githubusercontent.com/assets/1152236/13778940/8656d3f6-ea86-11e5-9ace-f961d995f253.png)
