### ISSUE TITLE
New front-end

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-edit-report-deprecated#66]
We just [shipped a new API](https://api-osm-comments-stagey-prod-246324559.us-east-1.elb.amazonaws.com/api/v1/stats). This currently gives changes every minute for every data team members with nodes, ways, relations, and tags created, modified or deleted. 

@rasagy @ajithranka @kepta @batpad @Rub21 - let's use this ticket to start outlining a new front-end. We should start fresh.

**Comment by geohacker** [comment]
Here's a sample from the API:

```json
{
  "id": 40839,
  "change_at": "2017-02-13T05:50:45.000Z",
  "uid": 1306,
  "nodes": {
    "c": 100,
    "d": 2,
    "m": 25
  },
  "ways": {
    "c": 15,
    "d": 2,
    "m": 11
  },
  "relations": {
    "c": 0,
    "d": 0,
    "m": 1
  },
  "changesets": [
    46036812
  ],
  "tags_created": {
    "foot": {
      "yes": 1
    },
    "horse": {
      "permissive": 1
    },
    "lanes": {
      "2": 1
    },
    "access": {
      "no": 1
    },
    "bicycle": {
      "yes": 1
    },
    "highway": {
      "service": 1
    },
    "service": {
      "alley": 1
    },
    "surface": {
      "asphalt": 1
    },
    "cycleway": {
      "no": 1
    },
    "sidewalk": {
      "none": 1
    },
    "motor_vehicle": {
      "permissive": 1
    }
  },
  "tags_modified": {
    "name": {
      "Karnataka State Highway 104": 1
    },
    "type": {
      "route": 1
    },
    "route": {
      "road": 1
    },
    "length": {
      "34": 1
    },
    "name:kn": {
      "ಕರ್ನಾಟಕ ರಾಜ್ಯ ಹೆದ್ದಾರಿ ೧೦೪": 1
    },
    "network": {
      "IN:SH:KA": 1
    }
  },
  "tags_deleted": {}
}
```

**Comment by rasagy** [comment]
We had a quick brainstorming session today on what are the goals, scenarios and rough idea on the UI:

**Goal**: To make it easy to follow the progress of a particular project (tag based), user(s), and overall performance of the Data team.

**IA + Use case**:
1. Landing page (_How is the Mapbox Data team doing?_)
    1. Total number of changesets (over time)
    2. Total created, modified, deleted (Aggregate ways/relations/nodes)
    3. Chart of top 3 tags that the team worked on (based on total changeset count)
2. Tags page: (_For a task/group of tags, how have we added data to OSM?_)
    1. Total number changesets (over time)
    2. Total created, modified, deleted (Aggregate ways/relations/nodes)
    3. Complete list of users and their contributions over time
3. Users page: (_For a user/group of users, what tags have been worked on, and how much?_)
    1. Total number changesets (over time)
    2. Total created, modified, deleted (Aggregate ways/relations/nodes)
    3. Chart of top 3 the user(s) worked on (based on total changeset count)

Will update this with some sketches that explain this further.

cc @geohacker @planemad @ajithranka @kepta @Rub21

**Comment by rasagy** [comment]
Layout sketch based on our discussions:

![edit-report-v2-sketch](https://cloud.githubusercontent.com/assets/1117531/23351833/93f8d434-fce9-11e6-9a31-e850ca1e38cd.jpg)

cc @ajithranka @kepta @geohacker

**Comment by ajithranka** [comment]
Shipped 🚀 https://www.mapbox.com/osm-edit-report/.
